### ISSUE TITLE
Can you recommended a crypter?

### ISSUE THREAD

**Issue by spaghetti1037** [UnamSanctam/UnamBinder#2]
Hey, can you recommend a crypter?

**Comment by Byblack36** [comment]
yes if you have any suggestions i was wondering too

**Comment by UnamSanctam** [comment]
Not really, I never use any crypters. Though this should stay undetected for Windows Defender for quite a while, if it does get detected then building a new build should make it undetected again since it's usually just MD5 checksum "detections".
