### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by DuyLvzy123** [UnamSanctam/UnamBinder#27]
how to bind bro?, because it's too complicated

**Comment by UnamSanctam** [comment]
Add the first file, then add the second file, then select any options you want such as maybe "Add Windows Defender exclusions" and "Run as Administrator".

**Comment by DuyLvzy123** [comment]
> Add the first file, then add the second file, then select any options you want such as maybe "Add Windows Defender exclusions" and "Run as Administrator".

<img width="581" alt="image" src="https://user-images.githubusercontent.com/99333895/170716162-cf9bb852-6562-4833-a67f-0a82cb87879b.png">
ayo bro??

**Comment by UnamSanctam** [comment]
Looks like it can't run the compiler, make sure that your antivirus isn't blocking it.

**Comment by DuyLvzy123** [comment]
> Looks like it can't run the compiler, make sure that your antivirus isn't blocking it.

I did

**Comment by UnamSanctam** [comment]
Then if it can't run it's due to something with your computer, you can alternatively build it as a managed assembly.

**Comment by DuyLvzy123** [comment]
> Looks like it can't run the compiler, make sure that your antivirus isn't blocking it.

what is this?
<img width="118" alt="image" src="https://user-images.githubusercontent.com/99333895/170717147-a94c5b17-2742-431e-bfbe-266448651ccb.png">
I turned it on and it worked but I haven't tried it yet

**Comment by UnamSanctam** [comment]
It means that it will build it as a managed assembly built in C# rather than a native assembly. https://github.com/UnamSanctam/UnamBinder/wiki#build-type

**Comment by DuyLvzy123** [comment]
> It means that it will build it as a managed assembly built in C# rather than a native assembly.

but It worked!!, thx u again
