### ISSUE TITLE
Why do u keep an copy of this file

### ISSUE THREAD

**Issue by ghost** [UnamSanctam/UnamBinder#28]
Im asking because its kinda weird? It could be a mistake or just intentional
https://github.com/UnamSanctam/UnamBinder/blob/master/UnamBinder/Forms/Builder.Designer%20-%20kopia.cs

**Comment by UnamSanctam** [comment]
Oh yeah it's unintentional, Visual Studio breaks the GUI quite a lot so I have to make a copy and replace it very often.
