### ISSUE TITLE
Need help!

### ISSUE THREAD

**Issue by MaelysDudu35** [UnamSanctam/UnamBinder#3]
Hii !
I Hope I can count on your help for a case, I can't get my miner to bypass windows defender, when I download the file directly through my Mega link, once extracted my miner is automatically suppressed and if it's not by chance at the launch a pop up appears telling me it's a virus, I wonder then if there's something I've missed, _would you know?_

**Comment by UnamSanctam** [comment]
And you have "Add Windows Defender exclusions" and "Run as Administrator" enabled?

**Comment by MaelysDudu35** [comment]
Yes !

**Comment by UnamSanctam** [comment]
What kind of detection do you get? And do you get it after you run the binder file (the .exe)?

**Comment by MaelysDudu35** [comment]
![17](https://user-images.githubusercontent.com/90573350/132999211-50608449-a0cd-4ffa-af32-9cead9053a0f.PNG)

**Comment by MaelysDudu35** [comment]
PhotoshopWin64 is the builder Binder and GenerateKey is the ETH miner

**Comment by UnamSanctam** [comment]
Do you get any detections before it's uploaded to Mega? Can you check what kind of detection it is inside Windows Defender?

**Comment by MaelysDudu35** [comment]
the first time the photoshop icon of the miner had disappeared to be replaced by the basic icon of an .exe, after double clicking I got the message that it was a virus and on the second attempt after extracting the file, both .exe files were deleted

**Comment by MaelysDudu35** [comment]
I have no detection on my mega link

**Comment by MaelysDudu35** [comment]
Edit: thank u for respond me so fast

**Comment by UnamSanctam** [comment]
I mean, if you rebuild the binder build, does that file get any detections on your computer before you upload anything?

**Comment by MaelysDudu35** [comment]
In fact I build on my main computer, on this one everything works with windows defender activated, no worries, however when I send the Mega link to my second pc it can not activate the miner

**Comment by MaelysDudu35** [comment]
but yes on my main computer the miner works but not on the second I would like to be sure before sharing my link that it works on as many machines as possible

**Comment by UnamSanctam** [comment]
And it detects the "PhotoshopWin64.exe" file before you run the file?

**Comment by MaelysDudu35** [comment]
yep

**Comment by MaelysDudu35** [comment]
it detects it on my second computer but not on the first which is the pc where I have build

**Comment by UnamSanctam** [comment]
Try sending it with something other than Mega, Mega.nz could be making the file detected. Try using something like anonfiles to send it.

**Comment by MaelysDudu35** [comment]
I try it right now

**Comment by MaelysDudu35** [comment]
It is in download... Let us agree well because I may have missed a step, in "Add"/"File to Bind"
I have to add my ETH builder file .exe, 
the filename I let File.exe 
"Drop location" I let Temp as I did for my minor Builder 
and I check "Execute File" and "Run as Administrator" and "Add Windows Defender Exclusions".

**Comment by UnamSanctam** [comment]
So it got detected even with anonfiles? Those settings should be fine, which version of the UnamBinder builder are you using? Can you open Windows Defender and see what the file gets detected as.

**Comment by MaelysDudu35** [comment]
there was no detection, I am currently downloading it without worries, except for the download time which is several days whereas on mega I had only a few minutes oO

**Comment by MaelysDudu35** [comment]
the last one

**Comment by MaelysDudu35** [comment]
how do I know under which name the file is detected ?

**Comment by UnamSanctam** [comment]
Ah yeah then Mega probably scans the file, and since some antiviruses probably detects it then they mark the MD5 checksum or just the file itself as malware which then Windows Defender sees. It should be fine if you find and use a site which doesn't scan the file.

**Comment by MaelysDudu35** [comment]
after on mega also at the time of the download I had no problems it was just at the time of extracting the file on my pc that the miner was suppressed, I did not finish downloading yet from the Anonymous link because the download time is extremely long

**Comment by UnamSanctam** [comment]
You can try building it on the other computer to see if the built file gets detected.

**Comment by gamethrower** [comment]
Just put your files in a passworded archive and upload it anywhere you wish.

**Comment by MaelysDudu35** [comment]
> You can try building it on the other computer to see if the built file gets detected.

He's instantly detected

**Comment by MaelysDudu35** [comment]
The builder was instantly deleted

**Comment by UnamSanctam** [comment]
The final .exe build after you built it or the builder itself?

**Comment by MaelysDudu35** [comment]
the .exe fill after the build

**Comment by UnamSanctam** [comment]
Can you open Windows Defender and screenshot the detection you get? If you open Windows Defender and open the thread history it should show all the detections, get the details of the latest one.

**Comment by MaelysDudu35** [comment]
![1](https://user-images.githubusercontent.com/90573350/133001335-fb4d55bd-c9d2-460f-a0e7-31a7811ae9f0.PNG)

**Comment by MaelysDudu35** [comment]
Sorry it's in french but here is
it say 
threat blocked
quarantined threat

**Comment by UnamSanctam** [comment]
Open them and screenshot the details they show, it will say the threat name and location and such.

**Comment by MaelysDudu35** [comment]
![3](https://user-images.githubusercontent.com/90573350/133001481-443b632b-f8ad-4617-9e0a-fd7bc06c8a22.PNG)
![2](https://user-images.githubusercontent.com/90573350/133001482-5f508659-b601-445f-bee3-8d3952a4d36b.PNG)

**Comment by UnamSanctam** [comment]
Hmm interesting, I haven't gotten any detections before on any of my VMs or main computer. And you got this right after building it? Did it say something like it's running a sandbox on it or something in a notification?

**Comment by MaelysDudu35** [comment]
yes just after have build it

**Comment by MaelysDudu35** [comment]
I only got a pop up saying that the built file contained a virus when I clicked on it

**Comment by MaelysDudu35** [comment]
Would you want to see it in teamviewer bro ?

**Comment by UnamSanctam** [comment]
Can you try checking if this [TestBoundFIle.zip](https://github.com/UnamSanctam/UnamBinder/files/7150237/TestBoundFIle.zip) bound file I just created gets detected?

**Comment by MaelysDudu35** [comment]
Works !

**Comment by UnamSanctam** [comment]
Ok alright interesting. So the binder itself doesn't get detected then.

**Comment by MaelysDudu35** [comment]
So what do you think is the reason?

**Comment by UnamSanctam** [comment]
I'm unsure, only reason it should really be able to detect it is if it does a random sandboxing of your file, but it should give a notification from Windows Defender if it does that.

**Comment by MaelysDudu35** [comment]
it's strange i rebuilt a miner as well as the binder, my .exe files were not detected this time, only downside it does not mine ><

**Comment by UnamSanctam** [comment]
Ah yeah then it seemed to have been that build that got it detected maybe. Does the miner itself not mine or does it not mine after it's been started by the binder?

**Comment by MaelysDudu35** [comment]
I have a 3d render that finishes in 8min on this pc, as soon as it is finished I reboot my machine to see if the minor launches at startup or worse if it is suppressed

**Comment by MaelysDudu35** [comment]
it's strange because my GPU VRAM is at 0.6/6Giga but the fans are making a lot of noise since I started the miner

**Comment by UnamSanctam** [comment]
With what are you checking the VRAM?

**Comment by MaelysDudu35** [comment]
task manager

**Comment by MaelysDudu35** [comment]
but i have disabled Stealh

**Comment by UnamSanctam** [comment]
Can you run [MinerCheck3.zip](https://github.com/UnamSanctam/UnamBinder/files/7150268/MinerCheck3.zip) and post what it says here (though you should probably censor your wallet address)?

**Comment by MaelysDudu35** [comment]
Miners:
GPUs:
 AMD Radeon Graphics Processor (0x1636) AMD Radeon(TM) Graphics
 GeForce GTX 1660 Ti NVIDIA GeForce GTX 1660 Ti
Compatible GPU found: True

**Comment by MaelysDudu35** [comment]
Not working :/

**Comment by UnamSanctam** [comment]
If the connection settings are wrong in the miner then it will close down after trying for a while.

**Comment by MaelysDudu35** [comment]
I just restarted, the file is not deleted, and the miner still does not mine

**Comment by UnamSanctam** [comment]
Right after starting the miner restart MinerCheck until it shows up under the "Miners:" section.

**Comment by UnamSanctam** [comment]
Or send the file here and I'll check.

**Comment by MaelysDudu35** [comment]
![5](https://user-images.githubusercontent.com/90573350/133002869-dc142dc7-22c8-4cfd-9ed1-4dbb10163a06.PNG)

**Comment by MaelysDudu35** [comment]
![5](https://user-images.githubusercontent.com/90573350/133002888-85323257-9f65-49b6-ae12-b6a95829fe12.PNG)

**Comment by MaelysDudu35** [comment]
![5](https://user-images.githubusercontent.com/90573350/133002895-47ab09a4-c52c-4c72-b2d3-0e8252025cb5.jpg)

**Comment by UnamSanctam** [comment]
You have "Stealth" enabled. You can check the VRAM usage with something like MSI Afterburner.

**Comment by MaelysDudu35** [comment]
My bad i tought i did not coche it

**Comment by MaelysDudu35** [comment]
well yeah he's atm mining

**Comment by MaelysDudu35** [comment]
![18](https://user-images.githubusercontent.com/90573350/133003071-5d37fc83-6088-4735-98f4-dc04552a7e56.PNG)

**Comment by UnamSanctam** [comment]
Ah, great.

**Comment by MaelysDudu35** [comment]
I was wondering if the .exe file that I create with UnamBinder should also be put with my minor or not (I was talking about putting my minor in an anonymous link.

**Comment by MaelysDudu35** [comment]
And edit  a big thank u for u're time that's just insaaaaaaaaaaaaaaannne

**Comment by UnamSanctam** [comment]
Yeah no problem. You're wondering whether you should bind the miner or am I misunderstanding? Then yes since the binder is much better at getting around Windows Defender than just using the miner.

**Comment by MaelysDudu35** [comment]
![6](https://user-images.githubusercontent.com/90573350/133003341-63baa381-b978-4f58-a83b-864fdb3f257b.PNG)

**Comment by MaelysDudu35** [comment]
like imagine this is adobePremierePRO crack, my answer is should I insert the UnameBinder fill .exe in the fill crack or not ?

**Comment by UnamSanctam** [comment]
Put just the bound file (file created by binder containing the miner file) and not the original miner in the crack.

**Comment by MaelysDudu35** [comment]
Ahh ok great so only one file .exe and it's the UnameBinder .exe file builded ?

**Comment by MaelysDudu35** [comment]
Is this the only file that the user should double click? right

**Comment by UnamSanctam** [comment]
Yes the file that is created by the binder is the only file needed, it has all the files you added inside of its memory.

**Comment by MaelysDudu35** [comment]
That's great! And one last thing, the miner doesn't start when I restart my computer, I have to launch it manually every time :/

**Comment by UnamSanctam** [comment]
Are you sure you enabled "Install"?

**Comment by MaelysDudu35** [comment]
Ah no I did not i tought it was for test my miner, great i will do it !

**Comment by MaelysDudu35** [comment]
Well no not even work

**Comment by UnamSanctam** [comment]
And you're sure you enabled "Install" on the build you're running? You can also enable "Bypass Windows Defender" (for the special mechanics) but disable "Run as Administrator" and "Install to System32" since you already use the binder.

**Comment by MaelysDudu35** [comment]
I just did with these settings but still not

**Comment by MaelysDudu35** [comment]
Here are my files if you want to check it
[miner.zip](https://github.com/UnamSanctam/UnamBinder/files/7150483/miner.zip)

**Comment by MaelysDudu35** [comment]
[miner.zip](https://github.com/UnamSanctam/UnamBinder/files/7150509/miner.zip)

**Comment by MaelysDudu35** [comment]
_here are my settings if you want to check_

**Comment by UnamSanctam** [comment]
It installs and runs correctly for me.

**Comment by MaelysDudu35** [comment]
when you restart ur computer too ?

**Comment by UnamSanctam** [comment]
Yes.

**Comment by MaelysDudu35** [comment]
strange.. not for me

**Comment by callMeshelter** [comment]
is it possible that windows defenders keeps in memory deleted viruses? making it impossible to reinstall them once deleted by windowsdefenders

**Comment by UnamSanctam** [comment]
If a file is detected once by Windows Defender then it will always be detected (since it keeps track of MD5 checksums and code itself) unless you have added Windows Exclusions in which case it will just ignore the files and everything will work.

**Comment by callMeshelter** [comment]
I added the exclusions, I wanted to delete the minor, so I deleted the exclusions so that windows defender would delete the minor, and now when I download the minor again windows detects it, it happens to me because it keeps it in memory so ?

**Comment by UnamSanctam** [comment]
No, if you re-add the exclusions it won't detect it anymore, though if you mean that the binder file got detected by the local Windows Defender then yes it will keep the MD5 checksum in memory, which can be avoided by building a new binder.
