### ISSUE TITLE
interesting

### ISSUE THREAD

**Issue by golxd** [UnamSanctam/UnamBinder#31]
if i use managed version and use confuser it will work on 32 and 64 bit? I don't understand why, but when I use the managed version and use confuser, in my tests it actually bypasses many antiviruses, but amount of successful installations is less than on the native version. I don't understand

**Comment by UnamSanctam** [comment]
Yes it should run on both 32-bit and 64-bit, could be ConfuserEx that's causing it, disable "Resource Encryption" in ConfuserEx if you aren't already since I think double encrypting could cause problems.

**Comment by golxd** [comment]
I dont see "Resource Encryption"  maybe "Resource Protection" ?

**Comment by UnamSanctam** [comment]
Yes.

**Comment by golxd** [comment]
okay, I'll try, thx. there are no more features that you want to disable?

**Comment by UnamSanctam** [comment]
No that's the only one I've read that could cause problems with double encryption/compression.
