### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by Brainshot** [UnamSanctam/UnamBinder#32]
What should I use? native C or Managed .NET for my RAT ?

**Comment by Brainshot** [comment]
Also can you add stealth and process killer in future to it?

**Comment by UnamSanctam** [comment]
> What should I use? native C or Managed .NET for my RAT ?

Depends on what you want to use, native C files can run on probably any system but you need a crypter if you want to crypt it, managed .NET needs .NET to run but you can use an obfuscator instead (easier to get than a crypter).

> Also can you add stealth and process killer in future to it?

No that wouldn't really serve any purpose, all it does is extract the files, run them (if chosen) and then exit.
