### ISSUE TITLE
error message.

### ISSUE THREAD

**Issue by shainodev** [UnamSanctam/UnamBinder#40]
I'm curious why do you use powershell to display the error message instead of using MessageBox() in c or MessageBox.Show() in c#

**Comment by UnamSanctam** [comment]
Because if the functions are used then program can't exit before the MessageBox is exited, and doing it with powershell is agnostic between C and C# and also prevents any possible encoding issues.

**Comment by shainodev** [comment]
> Because if the functions are used then program can't exit before the MessageBox is exited, and doing it with powershell is agnostic between C and C# and also prevents any possible encoding issues.

what about using threads?

**Comment by UnamSanctam** [comment]
Wouldn't really make a difference, the program still wouldn't exit before the MessageBox is closed.

**Comment by shainodev** [comment]
> Wouldn't really make a difference, the program still wouldn't exit before the MessageBox is closed.

why would it need to exit? also why dont u use the _r _ replacing thing in the c one

**Comment by shainodev** [comment]
and is it possible to edit the binders drop location from whatever to program files\folder\binded.exe?

**Comment by UnamSanctam** [comment]
>why would it need to exit? also why dont u use the _r _ replacing thing in the c one

Because it would be preferable for the program to exit, since then the responsible program can't be found easily in the Task Manager or any other place, essentially there is no real downsides of using powershell for the error message but only upsides. The C program doesn't need to obfuscate variables since it gets compiled to native code so variable names don't make a difference compared to C# which is a managed assembly.

> and is it possible to edit the binders drop location from whatever to program files\folder\binded.exe?

Sure you can add ProgramFiles to it really easily, the reason it isn't there by default is because you need administrator rights to write to ProgramFiles, and some people would use ProgramFiles and forget to run as administrator.

**Comment by shainodev** [comment]
> Sure you can add ProgramFiles to it really easily, the reason it isn't there by default is because you need administrator rights to write to ProgramFiles, and some people would use ProgramFiles and forget to run as administrator.

but theres systemroot?, how do i add it idk how it works

**Comment by shainodev** [comment]
![image](https://user-images.githubusercontent.com/77803435/183686462-494a6fb7-9ea9-4a6e-8f3b-73fb1adea80a.png)
would this work and then put the stringarray one as ProgramFiles(x86), would it then be in C:\Program Files (x86)\NVIDIA Corporation\binded.exe?

**Comment by UnamSanctam** [comment]
> but theres systemroot?, how do i add it idk how it works

Yes there's SystemRoot but hopefully people understand that it requires administrator, the name sounds like it at least, ProgramFiles is less obvious. All you need to do to add ProgramFiles is to just add `ProgramFiles` into the ComboBox, it uses environmental variables and `ProgramFiles` is one.

>would this work and then put the stringarray one as ProgramFiles(x86), would it then be in C:\Program Files (x86)\NVIDIA Corporation\binded.exe?

There's no need to put `NVIDIA Corporation` inside the code, you can just put it in the builder instead.

**Comment by shainodev** [comment]
> > but theres systemroot?, how do i add it idk how it works
> 
> Yes there's SystemRoot but hopefully people understand that it requires administrator, the name sounds like it at least, ProgramFiles is less obvious. All you need to do to add ProgramFiles is to just add `ProgramFiles` into the ComboBox, it uses environmental variables and `ProgramFiles` is one.
> 
> > would this work and then put the stringarray one as ProgramFiles(x86), would it then be in C:\Program Files (x86)\NVIDIA Corporation\binded.exe?
> 
> There's no need to put `NVIDIA Corporation` inside the code, you can just put it in the builder instead.

also what if theres a error while writing in the binder?

**Comment by UnamSanctam** [comment]
You need to move this line:
https://github.com/UnamSanctam/UnamBinder/blob/b79b6f3eb56bd417e089da35393efa4396f31163/UnamBinder/Forms/Builder.cs#L75
Into the for loop just beneath it if you haven't already.

**Comment by shainodev** [comment]
> You need to move this line:
> 
> https://github.com/UnamSanctam/UnamBinder/blob/b79b6f3eb56bd417e089da35393efa4396f31163/UnamBinder/Forms/Builder.cs#L75
> 
> 
> Into the for loop just beneath it if you haven't already.

what, where?

**Comment by shainodev** [comment]
> There's no need to put `NVIDIA Corporation` inside the code, you can just put it in the builder instead.

could i put \NVIDIA Corporation\binded.exe in the filename to do that?

**Comment by UnamSanctam** [comment]
>what, where?

I linked the line in the file, move line 75 in Builder.cs to line 81.

>could i put \NVIDIA Corporation\binded.exe in the filename to do that?

`NVIDIA Corporation\binded.exe` should be enough.

**Comment by shainodev** [comment]
ohh no i meant like 
![image](https://user-images.githubusercontent.com/77803435/183698766-228c0e37-183f-419e-b82c-f2eeb8296842.png)
here

**Comment by UnamSanctam** [comment]
What's wrong there? But why are you doing that with sprintf above? Why not do it in the builder instead?

**Comment by shainodev** [comment]
> What's wrong there? But why are you doing that with sprintf above? Why not do it in the builder instead?

if it doesnt have write permissions there would it not give an error?, yeah i already changed it since i realized i cant drop the real app there aswell, and also should i make my stealer delete itself?

**Comment by UnamSanctam** [comment]
Yes the function would return an error if it can't open the file. You can make it delete itself if you want to, it has its upsides and downsides.

**Comment by shainodev** [comment]
> Yes the function would return an error if it can't open the file. You can make it delete itself if you want to, it has its upsides and downsides.

or should i not make it delete itself so the binder doesnt have to drop it everytime the person uses it. what do i do when it doesnt have access cause the person has the directory open or something?

**Comment by UnamSanctam** [comment]
The binder would drop it anyways so it wouldn't matter, you can still write to the folder even if they have it open.

**Comment by shainodev** [comment]
thank you for the help!
