### ISSUE TITLE
Binder can't open .ico and file signing doesnt work

### ISSUE THREAD

**Issue by 5mirok5** [UnamSanctam/UnamBinder#5]
```resource.rc:2: unrecognized escape sequence
resource.rc:2: unrecognized escape sequence
resource.rc:2: unrecognized escape sequence
resource.rc:2: unrecognized escape sequence
resource.rc:2: unrecognized escape sequence
C:\Users\s\Desktop\ETC\UnamBinder\Compiler\MinGW64\bin\windres.exe: can't open icon file `C:\Users\s\Desktop\ETC\iconsI1111.ico': No such file or directory

C:\Users\s\Desktop\ETC\UnamBinder\Compiler\MinGW64\bin\windres.exe: resource.rc:9: syntax error
```
Full path: C:\Users\s\Desktop\ETC\icons\1111111.ico

![image](https://user-images.githubusercontent.com/42434556/133586754-d5926c95-4daf-40a8-a513-d1e025cc3003.png)

**Comment by UnamSanctam** [comment]
Don't name the icon 1111111, \1 is an escape sequence so that's how it interprets it, I guess I could escape the backslashes.

**Comment by 5mirok5** [comment]
> 
> 
> Don't name the icon 1111111, \1 is an escape sequence so that's how it interprets it, I guess I could escape the backslashes.

Thanks! But file signing still doesnt work
```
C:\Users\s\Desktop\ETC\UnamBinder\Compiler\MinGW64\bin\windres.exe: resource.rc:9: syntax error
```

**Comment by UnamSanctam** [comment]
What assembly settings are you importing? That seems like you use some weird versioning.

**Comment by 5mirok5** [comment]
> 
> 
> What assembly settings are you importing? That seems like you use some weird versioning.

I found the problem. Binder add extra chars in "version" sectino

**Comment by UnamSanctam** [comment]
Yes it correctly formats it, the versions should only contain numbers, maybe I'll make a check for it.

**Comment by 5mirok5** [comment]
> 
> 
> Yes it correctly formats it, the versions should only contain numbers, maybe I'll make a check for it.

Also your loader has the same troubles

**Comment by UnamSanctam** [comment]
It uses the same code though I didn't believe really think of anyone adding anything else but numbers.
