### ISSUE TITLE
Why is it detected virus in binder

### ISSUE THREAD

**Issue by N4ok1** [UnamSanctam/UnamBinder#55]
It detect the binder itself as a virus, why? it just join 2 files, why would there be a virus in it?

**Comment by UnamSanctam** [comment]
Because it deems that as potentially malicious. But antiviruses are a lot more complicated and advanced than just that, they do heuristic analysis with machine learning and such.

**Comment by N4ok1** [comment]
but VirusTotal have 40 detection is it still normal?

**Comment by UnamSanctam** [comment]
That's because it's been a while since the last release and I haven't had time to finish the update yet.

**Comment by N4ok1** [comment]
so there is no risk?

**Comment by UnamSanctam** [comment]
Depends on what you mean by risk, the binder itself isn't a virus (as you can see in the code in this repository), but the files you join together can of course be viruses.

**Comment by N4ok1** [comment]
i mean risk for me

**Comment by UnamSanctam** [comment]
The binder itself does not pose any risk for you, it's fully open source.

**Comment by N4ok1** [comment]
pkay thanks
