### ISSUE TITLE
Contains the following illegal special characters

### ISSUE THREAD

**Issue by TrafficRider** [UnamSanctam/UnamBinder#8]
Hello, maybe a stupid question, but how to bind them? It throws an error. These are silent xmr and eth miners
![биндер](https://user-images.githubusercontent.com/73399534/135644542-5350c298-4bc9-4665-abb5-93ea0137178d.PNG)

**Comment by UnamSanctam** [comment]
Your username has Cyrillic in it but the compiled only supports Ascii characters, try building it in a folder directly on your C: drive.
